apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
spec:
  to:
    kind: Service
    name: frontend-service  # Changed from frontend-svc to match oc new-app name
  port:
    targetPort: 8080  # Changed from 80 to 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect